//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArandaSW.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_role_privileges
    {
        public int id { get; set; }
        public Nullable<int> role_fk { get; set; }
        public Nullable<int> privilege_fk { get; set; }
    
        public virtual a_privilege a_privilege { get; set; }
        public virtual a_role a_role { get; set; }
    }
}
