//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArandaSW.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_user
    {
        public int id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string usr_name { get; set; }
        public string usr_password { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<int> role_fk { get; set; }
    
        public virtual a_role a_role { get; set; }
    }
}
