//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArandaSW.WebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArandaDBEntities : DbContext
    {
        public ArandaDBEntities()
            : base("name=ArandaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<a_privilege> a_privilege { get; set; }
        public virtual DbSet<a_role> a_role { get; set; }
        public virtual DbSet<a_role_privileges> a_role_privileges { get; set; }
        public virtual DbSet<a_section> a_section { get; set; }
        public virtual DbSet<a_user> a_user { get; set; }
    }
}
